### ISSUE TITLE
Waitress and swagger UI

### ISSUE THREAD

**Issue by CrabbyPete** [rdidyk/falcon-swagger-ui#5]
I am developing an application on window with Falcon and serving it with Waitress. I added the swagger ui and I get the following

Traceback (most recent call last):
  File "H:/Projects/nlp_api/nlp_api/app.py", line 114, in <module>
    serve( application, host='0.0.0.0', port=5000)
  File "H:\Projects\nlp_api\lib\site-packages\waitress\__init__.py", line 11, in serve
    server = _server(app, **kw)
  File "H:\Projects\nlp_api\lib\site-packages\waitress\server.py", line 85, in create_server
    sockinfo=sockinfo)
  File "H:\Projects\nlp_api\lib\site-packages\waitress\server.py", line 182, in __init__
    self.bind_server_socket()
  File "H:\Projects\nlp_api\lib\site-packages\waitress\server.py", line 294, in bind_server_socket
    self.bind(sockaddr)
  File "C:\DevTools\Python36\lib\asyncore.py", line 329, in bind
    return self.socket.bind(addr)
OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

**Comment by CrabbyPete** [comment]
I was serving on 0.0.0.0
