### ISSUE TITLE
Serving local schema

### ISSUE THREAD

**Issue by alysivji** [rdidyk/falcon-swagger-ui#8]
Thanks for this great library!

I'm following the example and was able to get the petstore schema loaded. I copied their `swagger.json` to serve locally and am running into an error.

```console
Traceback (most recent call last):
  File "/Users/alysivji/.virtualenvs/code_everyday370/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/Users/alysivji/.virtualenvs/code_everyday370/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/Users/alysivji/.virtualenvs/code_everyday370/lib/python3.7/site-packages/falcon/api.py", line 244, in __call__
    responder(req, resp, **params)
TypeError: __call__() missing 1 required positional argument: 'filepath'
```

Not sure if I'm setting it up correctly

```python
import falcon
from falcon_swagger_ui import register_swaggerui_app, StaticSinkAdapter

SWAGGERUI_URL = '/swagger'  # without trailing '/'
SCHEMA_URL = '/v2/swagger.json'

app = falcon.API()

app.add_sink(
    StaticSinkAdapter('/swagger.json'), SCHEMA_URL
)

register_swaggerui_app(app, SWAGGERUI_URL, SCHEMA_URL, config={
    'supportedSubmitMethods': ['get'],
})
```

Directory structure
```console
.
├── example.py
└── swagger.json
```

**Comment by alysivji** [comment]
I decided to create an endpoint that generates a swagger schema (via py2swagger).

```python
import argparse

import falcon
from py2swagger.plugins.falcon import FalconPy2SwaggerPlugin


class Py2SwaggerResource:
    def on_get(self, req, resp):
        arguments = argparse.Namespace(
            app="app:api", config=None, output=None, plugin="falcon"
        )
        swagger_part = FalconPy2SwaggerPlugin().run(arguments)

        resp.status = falcon.HTTP_OK
        resp.media = swagger_part
```

**Comment by rdidyk** [comment]
Hello,
I've updated example, please check

**Comment by alysivji** [comment]
Thanks @rdidyk!
